#!/bin/bash
# This script copies ROS package files generated by Simulink C/C++ coder to appropriate locations acording to ANPL ROS convention.
# Usage ./convert_anpl_ros_pkg model_name <generated_pkg_catkin_source_dir> <new_pkg_catkin_dir>
# Use the script if Simulink model changes and ROS package needs to be updated by copying it to the Matlab catkin workspace where the Coder generated package and running it.
# e.g. 
# cd matlab_catkin_ws
# ./convert_to_anpl_ros_pkg.sh Pure_Pursuit_With_VFH src ~/ANPL/infrastructure/catkin_ws/src/mrbsp_ros/controller_node
pkg_name=`echo "$1" | sed 's/./\L&/g'`

echo "Creating ANPL package inside $3 from $pkg_name in $2"

# delete the old files
rm -rf $3/$pkg_name/include
rm -rf $3/$pkg_name/src
rm -rf $3/$pkg_name/simulink_model
rm -rf $3/$pkg_name/temp

# create ANPL directory structure
mkdir -p $3/$pkg_name/include/$pkg_name
mkdir -p $3/$pkg_name/src/$pkg_name
mkdir -p $3/$pkg_name/simulink_model
mkdir -p $3/$pkg_name/temp

cp -r $2/$pkg_name/* $3/$pkg_name/temp

# move new C/C++ source files
mv $3/$pkg_name/temp/*.cpp  $3/$pkg_name/temp/*.c $3/$pkg_name/src/$pkg_name 2> /dev/null
# move new C/C++ headers
mv $3/$pkg_name/temp/*.h $3/$pkg_name/temp/*.hpp $3/$pkg_name/include/$pkg_name 2> /dev/null
# move new defines.txt
mv $3/$pkg_name/temp/defines.txt $3/$pkg_name/defines.txt 2> /dev/null


# copy the Simulink model used to generate new ROS package
cp $2/../$1.slx $3/$pkg_name/simulink_model
echo $2/../$0
cp $2/../$0 $3/$pkg_name/simulink_model # copy this script
echo "Done."

